### PR TITLE
[python3]solution for q-1112

### PR DESCRIPTION
**Pull request by ShubhamShaswat**

### CODE REVIEW

**Comment by ShubhamShaswat** [comment]
Looks fine for test case,code could be further improved,I will appreciate your feedback on this.

**Comment by innerpeacez** [comment]
# 948

**Comment by innerpeacez** [comment]
And you also need to modify README.md to point to your code.

for example:
```
[python3](solutions/python3/<filename>)
```

**Comment by innerpeacez** [comment]
ref: https://github.com/hi-code-room/leetcode/issues/948

**Comment by ShubhamShaswat** [comment]
I am on it

**Comment by innerpeacez** [comment]
> And you also need to modify README.md to point to your code.
> 
> for example:
> 
> ```
> [python3](solutions/python3/<filename>)
> ```

@ShubhamShaswat

**Comment by ShubhamShaswat** [comment]
@innerpeacez I have already modified the README.md in the solutions/python3. Do you want me to modified the main README.md file too?

**Comment by innerpeacez** [comment]
I mean the README.md file in the root directory

| 1112 | [拼写单词/Find Words That Can Be Formed by Characters](questions/1112-Find-Words-That-Can-Be-Formed-by-Characters-Easy.md) | [java](#leetcode),[python3](#leetcode),[go](#leetcode),[c](#leetcode),[c#](#leetcode),[cpp](#leetcode),[js](#leetcode) | 简单/Easy |

**Comment by ShubhamShaswat** [comment]
modified both README.md and README-EN.md in ROOT directory

**Comment by innerpeacez** [comment]
fix conflict please @ShubhamShaswat

**Comment by ShubhamShaswat** [comment]
done

**Comment by innerpeacez** [comment]
Thanks for your contribution @ShubhamShaswat

**Comment by innerpeacez** [comment]
Welcome to continue contributing  a new @ShubhamShaswat

**Comment by ShubhamShaswat** [comment]
Thanks @innerpeacez  I will try to contribute whatever I can.

**Pull request merged**
